version: 2

models:
  - name: int_orders
    description: Intermediate model combining order data with key info
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
      - name: order_status
        tests:
          - not_null

  - name: int_customers
    description: Intermediate model enriching customer data
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: customer_state
        tests:
          - not_null

  - name: int_payments
    description: Intermediate model summarizing payment info by order
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: total_payment
        tests:
          - not_null
