version: 2

models:
  - name: stg_orders
    description: Staging model for orders dataset
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
      - name: order_status
        tests:
          - not_null

  - name: stg_customers
    description: Staging model for customers dataset
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique
      - name: customer_unique_id
        tests:
          - not_null
      # - name: customer_zip_code_prefix
      #   tests:
      #     - not_null


  - name: stg_order_payments
    description: Staging model for order payments dataset
    columns:
      - name: order_id
        tests:
          - not_null
      - name: payment_type
        tests:
          - not_null
          - accepted_values:
              values: ['credit_card', 'voucher', 'boleto', 'debit_card', 'not_defined']
      - name: payment_value
        tests:
          - not_null

