version: 2

models:
  - name: orders
    description: Final fact table for order analytics
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: customer_id
        tests:
          - not_null
          - relationships:
              to: ref('stg_customers')
              field: customer_id

      - name: payment_type
        tests:
          - not_null
          - accepted_values:
              values: ['credit_card', 'boleto', 'debit_card', 'voucher']








  - name: dim_customers
    description: Dimension table for customers
    columns:
      - name: customer_id
        tests:
          - not_null
          - unique

  - name: fct_payments
    description: Fact table summarizing payments
    columns:
      - name: order_id
        tests:
          - not_null
          - unique
      - name: total_payment
        tests:
          - not_null

